# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Main.ui'
#
# Created: Fri Feb 14 21:30:52 2014
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1031, 699)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.moduleTabWidget = QtGui.QTabWidget(self.centralwidget)
        self.moduleTabWidget.setObjectName(_fromUtf8("moduleTabWidget"))
        self.tab_Jointer = QtGui.QWidget()
        self.tab_Jointer.setObjectName(_fromUtf8("tab_Jointer"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.tab_Jointer)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.setupTextTextBrowser = QtGui.QTextBrowser(self.tab_Jointer)
        self.setupTextTextBrowser.setEnabled(True)
        self.setupTextTextBrowser.setFocusPolicy(QtCore.Qt.NoFocus)
        self.setupTextTextBrowser.setFrameShape(QtGui.QFrame.NoFrame)
        self.setupTextTextBrowser.setFrameShadow(QtGui.QFrame.Plain)
        self.setupTextTextBrowser.setObjectName(_fromUtf8("setupTextTextBrowser"))
        self.verticalLayout_3.addWidget(self.setupTextTextBrowser)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.groupBox = QtGui.QGroupBox(self.tab_Jointer)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_5 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.gridLayout_7 = QtGui.QGridLayout()
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.selectAxisLabel = QtGui.QLabel(self.groupBox)
        self.selectAxisLabel.setObjectName(_fromUtf8("selectAxisLabel"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.selectAxisLabel)
        self.selectXYAxisComboBox = QtGui.QComboBox(self.groupBox)
        self.selectXYAxisComboBox.setObjectName(_fromUtf8("selectXYAxisComboBox"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.selectXYAxisComboBox)
        self.overTravelLabel = QtGui.QLabel(self.groupBox)
        self.overTravelLabel.setObjectName(_fromUtf8("overTravelLabel"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.overTravelLabel)
        self.overTravelLineEdit = QtGui.QLineEdit(self.groupBox)
        self.overTravelLineEdit.setObjectName(_fromUtf8("overTravelLineEdit"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.overTravelLineEdit)
        self.safeZHeightLabel = QtGui.QLabel(self.groupBox)
        self.safeZHeightLabel.setObjectName(_fromUtf8("safeZHeightLabel"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.safeZHeightLabel)
        self.safeZHeightLineEdit = QtGui.QLineEdit(self.groupBox)
        self.safeZHeightLineEdit.setObjectName(_fromUtf8("safeZHeightLineEdit"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.safeZHeightLineEdit)
        self.zAxisOffsetLabel_2 = QtGui.QLabel(self.groupBox)
        self.zAxisOffsetLabel_2.setObjectName(_fromUtf8("zAxisOffsetLabel_2"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.zAxisOffsetLabel_2)
        self.zAxisOffsetLineEdit_2 = QtGui.QLineEdit(self.groupBox)
        self.zAxisOffsetLineEdit_2.setObjectName(_fromUtf8("zAxisOffsetLineEdit_2"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.zAxisOffsetLineEdit_2)
        self.gridLayout_7.addLayout(self.formLayout, 0, 0, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_7, 0, 0, 1, 1)
        self.gridLayout_8 = QtGui.QGridLayout()
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.formLayout_7 = QtGui.QFormLayout()
        self.formLayout_7.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_7.setObjectName(_fromUtf8("formLayout_7"))
        self.cutPassesLabel = QtGui.QLabel(self.groupBox)
        self.cutPassesLabel.setObjectName(_fromUtf8("cutPassesLabel"))
        self.formLayout_7.setWidget(0, QtGui.QFormLayout.LabelRole, self.cutPassesLabel)
        self.cutPassesSpinBox = QtGui.QSpinBox(self.groupBox)
        self.cutPassesSpinBox.setObjectName(_fromUtf8("cutPassesSpinBox"))
        self.formLayout_7.setWidget(0, QtGui.QFormLayout.FieldRole, self.cutPassesSpinBox)
        self.cutOffsetLabel = QtGui.QLabel(self.groupBox)
        self.cutOffsetLabel.setObjectName(_fromUtf8("cutOffsetLabel"))
        self.formLayout_7.setWidget(1, QtGui.QFormLayout.LabelRole, self.cutOffsetLabel)
        self.cutOffsetLineEdit = QtGui.QLineEdit(self.groupBox)
        self.cutOffsetLineEdit.setObjectName(_fromUtf8("cutOffsetLineEdit"))
        self.formLayout_7.setWidget(1, QtGui.QFormLayout.FieldRole, self.cutOffsetLineEdit)
        self.cutPassSpindleSpeedLabel = QtGui.QLabel(self.groupBox)
        self.cutPassSpindleSpeedLabel.setObjectName(_fromUtf8("cutPassSpindleSpeedLabel"))
        self.formLayout_7.setWidget(2, QtGui.QFormLayout.LabelRole, self.cutPassSpindleSpeedLabel)
        self.cutPassSpindleSpeedLineEdit = QtGui.QLineEdit(self.groupBox)
        self.cutPassSpindleSpeedLineEdit.setObjectName(_fromUtf8("cutPassSpindleSpeedLineEdit"))
        self.formLayout_7.setWidget(2, QtGui.QFormLayout.FieldRole, self.cutPassSpindleSpeedLineEdit)
        self.cutPassFeedRateLabel = QtGui.QLabel(self.groupBox)
        self.cutPassFeedRateLabel.setObjectName(_fromUtf8("cutPassFeedRateLabel"))
        self.formLayout_7.setWidget(3, QtGui.QFormLayout.LabelRole, self.cutPassFeedRateLabel)
        self.cutPassFeedRateLineEdit = QtGui.QLineEdit(self.groupBox)
        self.cutPassFeedRateLineEdit.setObjectName(_fromUtf8("cutPassFeedRateLineEdit"))
        self.formLayout_7.setWidget(3, QtGui.QFormLayout.FieldRole, self.cutPassFeedRateLineEdit)
        self.gridLayout_8.addLayout(self.formLayout_7, 0, 0, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_8, 0, 1, 1, 1)
        self.gridLayout_10 = QtGui.QGridLayout()
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.formLayout_4 = QtGui.QFormLayout()
        self.formLayout_4.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_4.setObjectName(_fromUtf8("formLayout_4"))
        self.finalPassesLabel = QtGui.QLabel(self.groupBox)
        self.finalPassesLabel.setObjectName(_fromUtf8("finalPassesLabel"))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.LabelRole, self.finalPassesLabel)
        self.finalPassesSpinBox = QtGui.QSpinBox(self.groupBox)
        self.finalPassesSpinBox.setObjectName(_fromUtf8("finalPassesSpinBox"))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.FieldRole, self.finalPassesSpinBox)
        self.finalOffsetLabel = QtGui.QLabel(self.groupBox)
        self.finalOffsetLabel.setObjectName(_fromUtf8("finalOffsetLabel"))
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.LabelRole, self.finalOffsetLabel)
        self.finalOffsetLineEdit = QtGui.QLineEdit(self.groupBox)
        self.finalOffsetLineEdit.setObjectName(_fromUtf8("finalOffsetLineEdit"))
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.FieldRole, self.finalOffsetLineEdit)
        self.finalPassSpindleSpeedLabel = QtGui.QLabel(self.groupBox)
        self.finalPassSpindleSpeedLabel.setObjectName(_fromUtf8("finalPassSpindleSpeedLabel"))
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.LabelRole, self.finalPassSpindleSpeedLabel)
        self.finalPassSpindleSpeedLineEdit = QtGui.QLineEdit(self.groupBox)
        self.finalPassSpindleSpeedLineEdit.setObjectName(_fromUtf8("finalPassSpindleSpeedLineEdit"))
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.FieldRole, self.finalPassSpindleSpeedLineEdit)
        self.finalPassFeedRateLabel = QtGui.QLabel(self.groupBox)
        self.finalPassFeedRateLabel.setObjectName(_fromUtf8("finalPassFeedRateLabel"))
        self.formLayout_4.setWidget(3, QtGui.QFormLayout.LabelRole, self.finalPassFeedRateLabel)
        self.finalPassFeedRateLineEdit = QtGui.QLineEdit(self.groupBox)
        self.finalPassFeedRateLineEdit.setObjectName(_fromUtf8("finalPassFeedRateLineEdit"))
        self.formLayout_4.setWidget(3, QtGui.QFormLayout.FieldRole, self.finalPassFeedRateLineEdit)
        self.gridLayout_10.addLayout(self.formLayout_4, 0, 0, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_10, 0, 2, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox, 0, 0, 1, 1)
        self.groupBox_2 = QtGui.QGroupBox(self.tab_Jointer)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.gridLayout_6 = QtGui.QGridLayout()
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.formLayout_2 = QtGui.QFormLayout()
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.materialLengthLabel = QtGui.QLabel(self.groupBox_2)
        self.materialLengthLabel.setObjectName(_fromUtf8("materialLengthLabel"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.materialLengthLabel)
        self.materialLengthLineEdit = QtGui.QLineEdit(self.groupBox_2)
        self.materialLengthLineEdit.setObjectName(_fromUtf8("materialLengthLineEdit"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.materialLengthLineEdit)
        self.materialWidthLabel = QtGui.QLabel(self.groupBox_2)
        self.materialWidthLabel.setObjectName(_fromUtf8("materialWidthLabel"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.materialWidthLabel)
        self.materialWidthLineEdit = QtGui.QLineEdit(self.groupBox_2)
        self.materialWidthLineEdit.setObjectName(_fromUtf8("materialWidthLineEdit"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.materialWidthLineEdit)
        self.materialThicknessLabel = QtGui.QLabel(self.groupBox_2)
        self.materialThicknessLabel.setObjectName(_fromUtf8("materialThicknessLabel"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.materialThicknessLabel)
        self.materialThicknessLineEdit = QtGui.QLineEdit(self.groupBox_2)
        self.materialThicknessLineEdit.setObjectName(_fromUtf8("materialThicknessLineEdit"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.materialThicknessLineEdit)
        self.distFromOriginLabel = QtGui.QLabel(self.groupBox_2)
        self.distFromOriginLabel.setObjectName(_fromUtf8("distFromOriginLabel"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.LabelRole, self.distFromOriginLabel)
        self.distFromOriginLineEdit = QtGui.QLineEdit(self.groupBox_2)
        self.distFromOriginLineEdit.setObjectName(_fromUtf8("distFromOriginLineEdit"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.FieldRole, self.distFromOriginLineEdit)
        self.gridLayout_6.addLayout(self.formLayout_2, 0, 0, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_6, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_2, 0, 1, 1, 1)
        self.groupBox_3 = QtGui.QGroupBox(self.tab_Jointer)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.formLayout_3 = QtGui.QFormLayout()
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.toolDiameterLabel = QtGui.QLabel(self.groupBox_3)
        self.toolDiameterLabel.setObjectName(_fromUtf8("toolDiameterLabel"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.toolDiameterLabel)
        self.toolDiameterLineEdit = QtGui.QLineEdit(self.groupBox_3)
        self.toolDiameterLineEdit.setObjectName(_fromUtf8("toolDiameterLineEdit"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.toolDiameterLineEdit)
        self.cutterLengthLabel = QtGui.QLabel(self.groupBox_3)
        self.cutterLengthLabel.setObjectName(_fromUtf8("cutterLengthLabel"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.LabelRole, self.cutterLengthLabel)
        self.cutterLengthLineEdit = QtGui.QLineEdit(self.groupBox_3)
        self.cutterLengthLineEdit.setObjectName(_fromUtf8("cutterLengthLineEdit"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.FieldRole, self.cutterLengthLineEdit)
        self.toolStickOutLabel = QtGui.QLabel(self.groupBox_3)
        self.toolStickOutLabel.setObjectName(_fromUtf8("toolStickOutLabel"))
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.LabelRole, self.toolStickOutLabel)
        self.toolStickOutLineEdit = QtGui.QLineEdit(self.groupBox_3)
        self.toolStickOutLineEdit.setObjectName(_fromUtf8("toolStickOutLineEdit"))
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.FieldRole, self.toolStickOutLineEdit)
        self.gridLayout.addLayout(self.formLayout_3, 0, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_3, 0, 2, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_3)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.moduleTabWidget.addTab(self.tab_Jointer, _fromUtf8(""))
        self.tab_StraightCut = QtGui.QWidget()
        self.tab_StraightCut.setObjectName(_fromUtf8("tab_StraightCut"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.tab_StraightCut)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.setupTextTextBrowser_2 = QtGui.QTextBrowser(self.tab_StraightCut)
        self.setupTextTextBrowser_2.setObjectName(_fromUtf8("setupTextTextBrowser_2"))
        self.verticalLayout_5.addWidget(self.setupTextTextBrowser_2)
        self.gridLayout_9 = QtGui.QGridLayout()
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.groupBox_5 = QtGui.QGroupBox(self.tab_StraightCut)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.gridLayout_15 = QtGui.QGridLayout(self.groupBox_5)
        self.gridLayout_15.setObjectName(_fromUtf8("gridLayout_15"))
        self.gridLayout_14 = QtGui.QGridLayout()
        self.gridLayout_14.setObjectName(_fromUtf8("gridLayout_14"))
        self.formLayout_6 = QtGui.QFormLayout()
        self.formLayout_6.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_6.setObjectName(_fromUtf8("formLayout_6"))
        self.materialThicknessLabel_2 = QtGui.QLabel(self.groupBox_5)
        self.materialThicknessLabel_2.setObjectName(_fromUtf8("materialThicknessLabel_2"))
        self.formLayout_6.setWidget(2, QtGui.QFormLayout.LabelRole, self.materialThicknessLabel_2)
        self.materialThicknessLineEdit_2 = QtGui.QLineEdit(self.groupBox_5)
        self.materialThicknessLineEdit_2.setObjectName(_fromUtf8("materialThicknessLineEdit_2"))
        self.formLayout_6.setWidget(2, QtGui.QFormLayout.FieldRole, self.materialThicknessLineEdit_2)
        self.materialYDimensionLabel = QtGui.QLabel(self.groupBox_5)
        self.materialYDimensionLabel.setObjectName(_fromUtf8("materialYDimensionLabel"))
        self.formLayout_6.setWidget(1, QtGui.QFormLayout.LabelRole, self.materialYDimensionLabel)
        self.materialYDimensionLineEdit = QtGui.QLineEdit(self.groupBox_5)
        self.materialYDimensionLineEdit.setObjectName(_fromUtf8("materialYDimensionLineEdit"))
        self.formLayout_6.setWidget(1, QtGui.QFormLayout.FieldRole, self.materialYDimensionLineEdit)
        self.materialXDimensionLabel = QtGui.QLabel(self.groupBox_5)
        self.materialXDimensionLabel.setObjectName(_fromUtf8("materialXDimensionLabel"))
        self.formLayout_6.setWidget(0, QtGui.QFormLayout.LabelRole, self.materialXDimensionLabel)
        self.materialXDimensionLineEdit = QtGui.QLineEdit(self.groupBox_5)
        self.materialXDimensionLineEdit.setObjectName(_fromUtf8("materialXDimensionLineEdit"))
        self.formLayout_6.setWidget(0, QtGui.QFormLayout.FieldRole, self.materialXDimensionLineEdit)
        self.gridLayout_14.addLayout(self.formLayout_6, 0, 0, 1, 1)
        self.gridLayout_15.addLayout(self.gridLayout_14, 0, 0, 1, 1)
        self.gridLayout_9.addWidget(self.groupBox_5, 1, 1, 1, 1)
        self.gridLayout_11 = QtGui.QGridLayout()
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.groupBox_7 = QtGui.QGroupBox(self.tab_StraightCut)
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.groupBox_7)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.formLayout_8 = QtGui.QFormLayout()
        self.formLayout_8.setObjectName(_fromUtf8("formLayout_8"))
        self.xOriginLabel = QtGui.QLabel(self.groupBox_7)
        self.xOriginLabel.setObjectName(_fromUtf8("xOriginLabel"))
        self.formLayout_8.setWidget(0, QtGui.QFormLayout.LabelRole, self.xOriginLabel)
        self.xOriginLineEdit = QtGui.QLineEdit(self.groupBox_7)
        self.xOriginLineEdit.setObjectName(_fromUtf8("xOriginLineEdit"))
        self.formLayout_8.setWidget(0, QtGui.QFormLayout.FieldRole, self.xOriginLineEdit)
        self.yOriginLabel = QtGui.QLabel(self.groupBox_7)
        self.yOriginLabel.setObjectName(_fromUtf8("yOriginLabel"))
        self.formLayout_8.setWidget(1, QtGui.QFormLayout.LabelRole, self.yOriginLabel)
        self.yOriginLineEdit = QtGui.QLineEdit(self.groupBox_7)
        self.yOriginLineEdit.setObjectName(_fromUtf8("yOriginLineEdit"))
        self.formLayout_8.setWidget(1, QtGui.QFormLayout.FieldRole, self.yOriginLineEdit)
        self.verticalLayout_7.addLayout(self.formLayout_8)
        self.setOriginFromGrid_pushButton = QtGui.QPushButton(self.groupBox_7)
        self.setOriginFromGrid_pushButton.setObjectName(_fromUtf8("setOriginFromGrid_pushButton"))
        self.verticalLayout_7.addWidget(self.setOriginFromGrid_pushButton)
        self.verticalLayout_8.addLayout(self.verticalLayout_7)
        self.gridLayout_11.addWidget(self.groupBox_7, 0, 1, 1, 1)
        self.groupBox_4 = QtGui.QGroupBox(self.tab_StraightCut)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.gridLayout_13 = QtGui.QGridLayout(self.groupBox_4)
        self.gridLayout_13.setObjectName(_fromUtf8("gridLayout_13"))
        self.gridLayout_18 = QtGui.QGridLayout()
        self.gridLayout_18.setObjectName(_fromUtf8("gridLayout_18"))
        self.formLayout_13 = QtGui.QFormLayout()
        self.formLayout_13.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_13.setObjectName(_fromUtf8("formLayout_13"))
        self.rightSideOfVectorLabel = QtGui.QLabel(self.groupBox_4)
        self.rightSideOfVectorLabel.setObjectName(_fromUtf8("rightSideOfVectorLabel"))
        self.formLayout_13.setWidget(0, QtGui.QFormLayout.LabelRole, self.rightSideOfVectorLabel)
        self.rightSideOfVectorCheckBox = QtGui.QCheckBox(self.groupBox_4)
        self.rightSideOfVectorCheckBox.setChecked(True)
        self.rightSideOfVectorCheckBox.setObjectName(_fromUtf8("rightSideOfVectorCheckBox"))
        self.StraightRipVectorButtonGroup = QtGui.QButtonGroup(MainWindow)
        self.StraightRipVectorButtonGroup.setObjectName(_fromUtf8("StraightRipVectorButtonGroup"))
        self.StraightRipVectorButtonGroup.addButton(self.rightSideOfVectorCheckBox)
        self.formLayout_13.setWidget(0, QtGui.QFormLayout.FieldRole, self.rightSideOfVectorCheckBox)
        self.leftSideOfVectorLabel = QtGui.QLabel(self.groupBox_4)
        self.leftSideOfVectorLabel.setObjectName(_fromUtf8("leftSideOfVectorLabel"))
        self.formLayout_13.setWidget(1, QtGui.QFormLayout.LabelRole, self.leftSideOfVectorLabel)
        self.leftSideOfVectorCheckBox = QtGui.QCheckBox(self.groupBox_4)
        self.leftSideOfVectorCheckBox.setObjectName(_fromUtf8("leftSideOfVectorCheckBox"))
        self.StraightRipVectorButtonGroup.addButton(self.leftSideOfVectorCheckBox)
        self.formLayout_13.setWidget(1, QtGui.QFormLayout.FieldRole, self.leftSideOfVectorCheckBox)
        self.onVectorLabel = QtGui.QLabel(self.groupBox_4)
        self.onVectorLabel.setObjectName(_fromUtf8("onVectorLabel"))
        self.formLayout_13.setWidget(2, QtGui.QFormLayout.LabelRole, self.onVectorLabel)
        self.onVectorCheckBox = QtGui.QCheckBox(self.groupBox_4)
        self.onVectorCheckBox.setObjectName(_fromUtf8("onVectorCheckBox"))
        self.StraightRipVectorButtonGroup.addButton(self.onVectorCheckBox)
        self.formLayout_13.setWidget(2, QtGui.QFormLayout.FieldRole, self.onVectorCheckBox)
        self.cutReverseDirectionLabel = QtGui.QLabel(self.groupBox_4)
        self.cutReverseDirectionLabel.setObjectName(_fromUtf8("cutReverseDirectionLabel"))
        self.formLayout_13.setWidget(3, QtGui.QFormLayout.LabelRole, self.cutReverseDirectionLabel)
        self.cutReverseDirectionCheckBox = QtGui.QCheckBox(self.groupBox_4)
        self.cutReverseDirectionCheckBox.setObjectName(_fromUtf8("cutReverseDirectionCheckBox"))
        self.formLayout_13.setWidget(3, QtGui.QFormLayout.FieldRole, self.cutReverseDirectionCheckBox)
        self.gridLayout_18.addLayout(self.formLayout_13, 0, 0, 1, 1)
        self.gridLayout_13.addLayout(self.gridLayout_18, 0, 1, 1, 1)
        self.gridLayout_12 = QtGui.QGridLayout()
        self.gridLayout_12.setObjectName(_fromUtf8("gridLayout_12"))
        self.formLayout_5 = QtGui.QFormLayout()
        self.formLayout_5.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_5.setObjectName(_fromUtf8("formLayout_5"))
        self.p1XLabel = QtGui.QLabel(self.groupBox_4)
        self.p1XLabel.setObjectName(_fromUtf8("p1XLabel"))
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.LabelRole, self.p1XLabel)
        self.p1XLineEdit = QtGui.QLineEdit(self.groupBox_4)
        self.p1XLineEdit.setObjectName(_fromUtf8("p1XLineEdit"))
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.FieldRole, self.p1XLineEdit)
        self.p1YLabel = QtGui.QLabel(self.groupBox_4)
        self.p1YLabel.setObjectName(_fromUtf8("p1YLabel"))
        self.formLayout_5.setWidget(1, QtGui.QFormLayout.LabelRole, self.p1YLabel)
        self.p1YLineEdit = QtGui.QLineEdit(self.groupBox_4)
        self.p1YLineEdit.setObjectName(_fromUtf8("p1YLineEdit"))
        self.formLayout_5.setWidget(1, QtGui.QFormLayout.FieldRole, self.p1YLineEdit)
        self.p2XLabel = QtGui.QLabel(self.groupBox_4)
        self.p2XLabel.setObjectName(_fromUtf8("p2XLabel"))
        self.formLayout_5.setWidget(2, QtGui.QFormLayout.LabelRole, self.p2XLabel)
        self.p2XLineEdit = QtGui.QLineEdit(self.groupBox_4)
        self.p2XLineEdit.setObjectName(_fromUtf8("p2XLineEdit"))
        self.formLayout_5.setWidget(2, QtGui.QFormLayout.FieldRole, self.p2XLineEdit)
        self.p2YLabel = QtGui.QLabel(self.groupBox_4)
        self.p2YLabel.setObjectName(_fromUtf8("p2YLabel"))
        self.formLayout_5.setWidget(3, QtGui.QFormLayout.LabelRole, self.p2YLabel)
        self.p2YLineEdit = QtGui.QLineEdit(self.groupBox_4)
        self.p2YLineEdit.setObjectName(_fromUtf8("p2YLineEdit"))
        self.formLayout_5.setWidget(3, QtGui.QFormLayout.FieldRole, self.p2YLineEdit)
        self.gridLayout_12.addLayout(self.formLayout_5, 0, 0, 1, 1)
        self.gridLayout_13.addLayout(self.gridLayout_12, 0, 0, 1, 1)
        self.gridLayout_11.addWidget(self.groupBox_4, 0, 2, 1, 1)
        self.gridLayout_9.addLayout(self.gridLayout_11, 1, 0, 1, 1)
        self.groupBox_6 = QtGui.QGroupBox(self.tab_StraightCut)
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.gridLayout_17 = QtGui.QGridLayout(self.groupBox_6)
        self.gridLayout_17.setObjectName(_fromUtf8("gridLayout_17"))
        self.gridLayout_16 = QtGui.QGridLayout()
        self.gridLayout_16.setObjectName(_fromUtf8("gridLayout_16"))
        self.formLayout_9 = QtGui.QFormLayout()
        self.formLayout_9.setObjectName(_fromUtf8("formLayout_9"))
        self.toolDiameterLabel_3 = QtGui.QLabel(self.groupBox_6)
        self.toolDiameterLabel_3.setObjectName(_fromUtf8("toolDiameterLabel_3"))
        self.formLayout_9.setWidget(0, QtGui.QFormLayout.LabelRole, self.toolDiameterLabel_3)
        self.toolDiameterLineEdit_3 = QtGui.QLineEdit(self.groupBox_6)
        self.toolDiameterLineEdit_3.setObjectName(_fromUtf8("toolDiameterLineEdit_3"))
        self.formLayout_9.setWidget(0, QtGui.QFormLayout.FieldRole, self.toolDiameterLineEdit_3)
        self.cutterLengthLabel_3 = QtGui.QLabel(self.groupBox_6)
        self.cutterLengthLabel_3.setObjectName(_fromUtf8("cutterLengthLabel_3"))
        self.formLayout_9.setWidget(1, QtGui.QFormLayout.LabelRole, self.cutterLengthLabel_3)
        self.cutterLengthLineEdit_3 = QtGui.QLineEdit(self.groupBox_6)
        self.cutterLengthLineEdit_3.setObjectName(_fromUtf8("cutterLengthLineEdit_3"))
        self.formLayout_9.setWidget(1, QtGui.QFormLayout.FieldRole, self.cutterLengthLineEdit_3)
        self.toolStickOutLabel_3 = QtGui.QLabel(self.groupBox_6)
        self.toolStickOutLabel_3.setObjectName(_fromUtf8("toolStickOutLabel_3"))
        self.formLayout_9.setWidget(2, QtGui.QFormLayout.LabelRole, self.toolStickOutLabel_3)
        self.toolStickOutLineEdit_3 = QtGui.QLineEdit(self.groupBox_6)
        self.toolStickOutLineEdit_3.setObjectName(_fromUtf8("toolStickOutLineEdit_3"))
        self.formLayout_9.setWidget(2, QtGui.QFormLayout.FieldRole, self.toolStickOutLineEdit_3)
        self.gridLayout_16.addLayout(self.formLayout_9, 0, 0, 1, 1)
        self.gridLayout_17.addLayout(self.gridLayout_16, 0, 0, 1, 1)
        self.gridLayout_9.addWidget(self.groupBox_6, 1, 2, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout_9)
        self.verticalLayout_6.addLayout(self.verticalLayout_5)
        self.gridLayout_25 = QtGui.QGridLayout()
        self.gridLayout_25.setObjectName(_fromUtf8("gridLayout_25"))
        self.groupBox_8 = QtGui.QGroupBox(self.tab_StraightCut)
        self.groupBox_8.setObjectName(_fromUtf8("groupBox_8"))
        self.gridLayout_20 = QtGui.QGridLayout(self.groupBox_8)
        self.gridLayout_20.setObjectName(_fromUtf8("gridLayout_20"))
        self.gridLayout_19 = QtGui.QGridLayout()
        self.gridLayout_19.setObjectName(_fromUtf8("gridLayout_19"))
        self.formLayout_10 = QtGui.QFormLayout()
        self.formLayout_10.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_10.setObjectName(_fromUtf8("formLayout_10"))
        self.safeZHeightLabel_2 = QtGui.QLabel(self.groupBox_8)
        self.safeZHeightLabel_2.setObjectName(_fromUtf8("safeZHeightLabel_2"))
        self.formLayout_10.setWidget(0, QtGui.QFormLayout.LabelRole, self.safeZHeightLabel_2)
        self.safeZHeightLineEdit_2 = QtGui.QLineEdit(self.groupBox_8)
        self.safeZHeightLineEdit_2.setObjectName(_fromUtf8("safeZHeightLineEdit_2"))
        self.formLayout_10.setWidget(0, QtGui.QFormLayout.FieldRole, self.safeZHeightLineEdit_2)
        self.overTravelLabel_2 = QtGui.QLabel(self.groupBox_8)
        self.overTravelLabel_2.setObjectName(_fromUtf8("overTravelLabel_2"))
        self.formLayout_10.setWidget(1, QtGui.QFormLayout.LabelRole, self.overTravelLabel_2)
        self.overTravelLineEdit_2 = QtGui.QLineEdit(self.groupBox_8)
        self.overTravelLineEdit_2.setObjectName(_fromUtf8("overTravelLineEdit_2"))
        self.formLayout_10.setWidget(1, QtGui.QFormLayout.FieldRole, self.overTravelLineEdit_2)
        self.zAxisOffsetLabel = QtGui.QLabel(self.groupBox_8)
        self.zAxisOffsetLabel.setObjectName(_fromUtf8("zAxisOffsetLabel"))
        self.formLayout_10.setWidget(2, QtGui.QFormLayout.LabelRole, self.zAxisOffsetLabel)
        self.zAxisOffsetLineEdit = QtGui.QLineEdit(self.groupBox_8)
        self.zAxisOffsetLineEdit.setObjectName(_fromUtf8("zAxisOffsetLineEdit"))
        self.formLayout_10.setWidget(2, QtGui.QFormLayout.FieldRole, self.zAxisOffsetLineEdit)
        self.horizontalNibbleLabel = QtGui.QLabel(self.groupBox_8)
        self.horizontalNibbleLabel.setObjectName(_fromUtf8("horizontalNibbleLabel"))
        self.formLayout_10.setWidget(3, QtGui.QFormLayout.LabelRole, self.horizontalNibbleLabel)
        self.horizontalNibbleCheckBox = QtGui.QCheckBox(self.groupBox_8)
        self.horizontalNibbleCheckBox.setObjectName(_fromUtf8("horizontalNibbleCheckBox"))
        self.formLayout_10.setWidget(3, QtGui.QFormLayout.FieldRole, self.horizontalNibbleCheckBox)
        self.horizontalNibbleOffsetLabel = QtGui.QLabel(self.groupBox_8)
        self.horizontalNibbleOffsetLabel.setObjectName(_fromUtf8("horizontalNibbleOffsetLabel"))
        self.formLayout_10.setWidget(4, QtGui.QFormLayout.LabelRole, self.horizontalNibbleOffsetLabel)
        self.horizontalNibbleOffsetLineEdit = QtGui.QLineEdit(self.groupBox_8)
        self.horizontalNibbleOffsetLineEdit.setObjectName(_fromUtf8("horizontalNibbleOffsetLineEdit"))
        self.formLayout_10.setWidget(4, QtGui.QFormLayout.FieldRole, self.horizontalNibbleOffsetLineEdit)
        self.gridLayout_19.addLayout(self.formLayout_10, 0, 0, 1, 1)
        self.gridLayout_20.addLayout(self.gridLayout_19, 0, 0, 1, 1)
        self.gridLayout_22 = QtGui.QGridLayout()
        self.gridLayout_22.setObjectName(_fromUtf8("gridLayout_22"))
        self.formLayout_12 = QtGui.QFormLayout()
        self.formLayout_12.setObjectName(_fromUtf8("formLayout_12"))
        self.finalPassesLabel_2 = QtGui.QLabel(self.groupBox_8)
        self.finalPassesLabel_2.setObjectName(_fromUtf8("finalPassesLabel_2"))
        self.formLayout_12.setWidget(0, QtGui.QFormLayout.LabelRole, self.finalPassesLabel_2)
        self.finalPassesSpinBox_2 = QtGui.QSpinBox(self.groupBox_8)
        self.finalPassesSpinBox_2.setObjectName(_fromUtf8("finalPassesSpinBox_2"))
        self.formLayout_12.setWidget(0, QtGui.QFormLayout.FieldRole, self.finalPassesSpinBox_2)
        self.finalOffsetLabel_2 = QtGui.QLabel(self.groupBox_8)
        self.finalOffsetLabel_2.setObjectName(_fromUtf8("finalOffsetLabel_2"))
        self.formLayout_12.setWidget(1, QtGui.QFormLayout.LabelRole, self.finalOffsetLabel_2)
        self.finalOffsetLineEdit_2 = QtGui.QLineEdit(self.groupBox_8)
        self.finalOffsetLineEdit_2.setObjectName(_fromUtf8("finalOffsetLineEdit_2"))
        self.formLayout_12.setWidget(1, QtGui.QFormLayout.FieldRole, self.finalOffsetLineEdit_2)
        self.finalPassSpindleSpeedLabel_2 = QtGui.QLabel(self.groupBox_8)
        self.finalPassSpindleSpeedLabel_2.setObjectName(_fromUtf8("finalPassSpindleSpeedLabel_2"))
        self.formLayout_12.setWidget(2, QtGui.QFormLayout.LabelRole, self.finalPassSpindleSpeedLabel_2)
        self.finalPassSpindleSpeedLineEdit_2 = QtGui.QLineEdit(self.groupBox_8)
        self.finalPassSpindleSpeedLineEdit_2.setObjectName(_fromUtf8("finalPassSpindleSpeedLineEdit_2"))
        self.formLayout_12.setWidget(2, QtGui.QFormLayout.FieldRole, self.finalPassSpindleSpeedLineEdit_2)
        self.finalPassFeedRateLabel_2 = QtGui.QLabel(self.groupBox_8)
        self.finalPassFeedRateLabel_2.setObjectName(_fromUtf8("finalPassFeedRateLabel_2"))
        self.formLayout_12.setWidget(3, QtGui.QFormLayout.LabelRole, self.finalPassFeedRateLabel_2)
        self.finalPassFeedRateLineEdit_2 = QtGui.QLineEdit(self.groupBox_8)
        self.finalPassFeedRateLineEdit_2.setObjectName(_fromUtf8("finalPassFeedRateLineEdit_2"))
        self.formLayout_12.setWidget(3, QtGui.QFormLayout.FieldRole, self.finalPassFeedRateLineEdit_2)
        self.gridLayout_22.addLayout(self.formLayout_12, 0, 0, 1, 1)
        self.gridLayout_20.addLayout(self.gridLayout_22, 0, 2, 1, 1)
        self.gridLayout_21 = QtGui.QGridLayout()
        self.gridLayout_21.setObjectName(_fromUtf8("gridLayout_21"))
        self.formLayout_11 = QtGui.QFormLayout()
        self.formLayout_11.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_11.setObjectName(_fromUtf8("formLayout_11"))
        self.cutPassesLabel_2 = QtGui.QLabel(self.groupBox_8)
        self.cutPassesLabel_2.setObjectName(_fromUtf8("cutPassesLabel_2"))
        self.formLayout_11.setWidget(0, QtGui.QFormLayout.LabelRole, self.cutPassesLabel_2)
        self.cutPassesSpinBox_2 = QtGui.QSpinBox(self.groupBox_8)
        self.cutPassesSpinBox_2.setObjectName(_fromUtf8("cutPassesSpinBox_2"))
        self.formLayout_11.setWidget(0, QtGui.QFormLayout.FieldRole, self.cutPassesSpinBox_2)
        self.cutOffsetLabel_2 = QtGui.QLabel(self.groupBox_8)
        self.cutOffsetLabel_2.setObjectName(_fromUtf8("cutOffsetLabel_2"))
        self.formLayout_11.setWidget(1, QtGui.QFormLayout.LabelRole, self.cutOffsetLabel_2)
        self.cutOffsetLineEdit_2 = QtGui.QLineEdit(self.groupBox_8)
        self.cutOffsetLineEdit_2.setObjectName(_fromUtf8("cutOffsetLineEdit_2"))
        self.formLayout_11.setWidget(1, QtGui.QFormLayout.FieldRole, self.cutOffsetLineEdit_2)
        self.cutPassSpindleSpeedLabel_2 = QtGui.QLabel(self.groupBox_8)
        self.cutPassSpindleSpeedLabel_2.setObjectName(_fromUtf8("cutPassSpindleSpeedLabel_2"))
        self.formLayout_11.setWidget(2, QtGui.QFormLayout.LabelRole, self.cutPassSpindleSpeedLabel_2)
        self.cutPassSpindleSpeedLineEdit_2 = QtGui.QLineEdit(self.groupBox_8)
        self.cutPassSpindleSpeedLineEdit_2.setObjectName(_fromUtf8("cutPassSpindleSpeedLineEdit_2"))
        self.formLayout_11.setWidget(2, QtGui.QFormLayout.FieldRole, self.cutPassSpindleSpeedLineEdit_2)
        self.cutPassFeedRateLabel_2 = QtGui.QLabel(self.groupBox_8)
        self.cutPassFeedRateLabel_2.setObjectName(_fromUtf8("cutPassFeedRateLabel_2"))
        self.formLayout_11.setWidget(3, QtGui.QFormLayout.LabelRole, self.cutPassFeedRateLabel_2)
        self.cutPassFeedRateLineEdit_2 = QtGui.QLineEdit(self.groupBox_8)
        self.cutPassFeedRateLineEdit_2.setObjectName(_fromUtf8("cutPassFeedRateLineEdit_2"))
        self.formLayout_11.setWidget(3, QtGui.QFormLayout.FieldRole, self.cutPassFeedRateLineEdit_2)
        self.gridLayout_21.addLayout(self.formLayout_11, 0, 0, 1, 1)
        self.gridLayout_20.addLayout(self.gridLayout_21, 0, 1, 1, 1)
        self.gridLayout_25.addWidget(self.groupBox_8, 0, 0, 1, 1)
        self.verticalLayout_6.addLayout(self.gridLayout_25)
        self.moduleTabWidget.addTab(self.tab_StraightCut, _fromUtf8(""))
        self.verticalLayout.addWidget(self.moduleTabWidget)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.launchFeedAndSpeeds_pushButton = QtGui.QPushButton(self.centralwidget)
        self.launchFeedAndSpeeds_pushButton.setObjectName(_fromUtf8("launchFeedAndSpeeds_pushButton"))
        self.horizontalLayout_2.addWidget(self.launchFeedAndSpeeds_pushButton)
        self.loadTool_pushButton = QtGui.QPushButton(self.centralwidget)
        self.loadTool_pushButton.setObjectName(_fromUtf8("loadTool_pushButton"))
        self.horizontalLayout_2.addWidget(self.loadTool_pushButton)
        self.generateGCode_pushButton = QtGui.QPushButton(self.centralwidget)
        self.generateGCode_pushButton.setAutoDefault(True)
        self.generateGCode_pushButton.setObjectName(_fromUtf8("generateGCode_pushButton"))
        self.horizontalLayout_2.addWidget(self.generateGCode_pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1031, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuSettings = QtGui.QMenu(self.menubar)
        self.menuSettings.setObjectName(_fromUtf8("menuSettings"))
        self.menuTools = QtGui.QMenu(self.menubar)
        self.menuTools.setObjectName(_fromUtf8("menuTools"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionMachine = QtGui.QAction(MainWindow)
        self.actionMachine.setObjectName(_fromUtf8("actionMachine"))
        self.actionGrid = QtGui.QAction(MainWindow)
        self.actionGrid.setObjectName(_fromUtf8("actionGrid"))
        self.actionPreamble = QtGui.QAction(MainWindow)
        self.actionPreamble.setObjectName(_fromUtf8("actionPreamble"))
        self.actionPostamble = QtGui.QAction(MainWindow)
        self.actionPostamble.setObjectName(_fromUtf8("actionPostamble"))
        self.actionCalc_Work_Offset = QtGui.QAction(MainWindow)
        self.actionCalc_Work_Offset.setObjectName(_fromUtf8("actionCalc_Work_Offset"))
        self.actionTool_Database = QtGui.QAction(MainWindow)
        self.actionTool_Database.setObjectName(_fromUtf8("actionTool_Database"))
        self.actionDefault_GCode_Folder = QtGui.QAction(MainWindow)
        self.actionDefault_GCode_Folder.setObjectName(_fromUtf8("actionDefault_GCode_Folder"))
        self.menuFile.addAction(self.actionExit)
        self.menuSettings.addAction(self.actionMachine)
        self.menuSettings.addAction(self.actionGrid)
        self.menuSettings.addAction(self.actionPreamble)
        self.menuSettings.addAction(self.actionPostamble)
        self.menuSettings.addAction(self.actionDefault_GCode_Folder)
        self.menuTools.addAction(self.actionCalc_Work_Offset)
        self.menuTools.addAction(self.actionTool_Database)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())

        self.retranslateUi(MainWindow)
        self.moduleTabWidget.setCurrentIndex(1)
        QtCore.QObject.connect(self.actionExit, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.selectXYAxisComboBox, self.overTravelLineEdit)
        MainWindow.setTabOrder(self.overTravelLineEdit, self.safeZHeightLineEdit)
        MainWindow.setTabOrder(self.safeZHeightLineEdit, self.zAxisOffsetLineEdit_2)
        MainWindow.setTabOrder(self.zAxisOffsetLineEdit_2, self.cutPassesSpinBox)
        MainWindow.setTabOrder(self.cutPassesSpinBox, self.cutOffsetLineEdit)
        MainWindow.setTabOrder(self.cutOffsetLineEdit, self.cutPassSpindleSpeedLineEdit)
        MainWindow.setTabOrder(self.cutPassSpindleSpeedLineEdit, self.cutPassFeedRateLineEdit)
        MainWindow.setTabOrder(self.cutPassFeedRateLineEdit, self.finalPassesSpinBox)
        MainWindow.setTabOrder(self.finalPassesSpinBox, self.finalOffsetLineEdit)
        MainWindow.setTabOrder(self.finalOffsetLineEdit, self.finalPassSpindleSpeedLineEdit)
        MainWindow.setTabOrder(self.finalPassSpindleSpeedLineEdit, self.finalPassFeedRateLineEdit)
        MainWindow.setTabOrder(self.finalPassFeedRateLineEdit, self.materialLengthLineEdit)
        MainWindow.setTabOrder(self.materialLengthLineEdit, self.materialWidthLineEdit)
        MainWindow.setTabOrder(self.materialWidthLineEdit, self.materialThicknessLineEdit)
        MainWindow.setTabOrder(self.materialThicknessLineEdit, self.distFromOriginLineEdit)
        MainWindow.setTabOrder(self.distFromOriginLineEdit, self.toolDiameterLineEdit)
        MainWindow.setTabOrder(self.toolDiameterLineEdit, self.cutterLengthLineEdit)
        MainWindow.setTabOrder(self.cutterLengthLineEdit, self.toolStickOutLineEdit)
        MainWindow.setTabOrder(self.toolStickOutLineEdit, self.launchFeedAndSpeeds_pushButton)
        MainWindow.setTabOrder(self.launchFeedAndSpeeds_pushButton, self.loadTool_pushButton)
        MainWindow.setTabOrder(self.loadTool_pushButton, self.generateGCode_pushButton)
        MainWindow.setTabOrder(self.generateGCode_pushButton, self.moduleTabWidget)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "CNC Woodworking g-code Generator", None))
        self.groupBox.setTitle(_translate("MainWindow", "Operation Properties", None))
        self.selectAxisLabel.setText(_translate("MainWindow", "Select Axis", None))
        self.overTravelLabel.setText(_translate("MainWindow", "Over Travel", None))
        self.safeZHeightLabel.setText(_translate("MainWindow", "Safe Z Height", None))
        self.zAxisOffsetLabel_2.setText(_translate("MainWindow", "Z Axis Offset", None))
        self.cutPassesLabel.setText(_translate("MainWindow", "Cut Passes", None))
        self.cutOffsetLabel.setText(_translate("MainWindow", "Cut Offset", None))
        self.cutPassSpindleSpeedLabel.setText(_translate("MainWindow", "Cut Pass Spindle Speed", None))
        self.cutPassFeedRateLabel.setText(_translate("MainWindow", "Cut Pass Feed Rate", None))
        self.finalPassesLabel.setText(_translate("MainWindow", "Final Passes", None))
        self.finalOffsetLabel.setText(_translate("MainWindow", "Final Offset", None))
        self.finalPassSpindleSpeedLabel.setText(_translate("MainWindow", "Final Pass Spindle Speed", None))
        self.finalPassFeedRateLabel.setText(_translate("MainWindow", "Final Pass Feed Rate", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "Material Properties", None))
        self.materialLengthLabel.setText(_translate("MainWindow", "Material Length", None))
        self.materialWidthLabel.setText(_translate("MainWindow", "Material Width", None))
        self.materialThicknessLabel.setText(_translate("MainWindow", "Material Thickness", None))
        self.distFromOriginLabel.setText(_translate("MainWindow", "Dist from Origin", None))
        self.groupBox_3.setTitle(_translate("MainWindow", "Tool Properties", None))
        self.toolDiameterLabel.setText(_translate("MainWindow", "Tool Diameter", None))
        self.cutterLengthLabel.setText(_translate("MainWindow", "Cutter Length", None))
        self.toolStickOutLabel.setText(_translate("MainWindow", "Tool Stick Out", None))
        self.moduleTabWidget.setTabText(self.moduleTabWidget.indexOf(self.tab_Jointer), _translate("MainWindow", "Jointer", None))
        self.groupBox_5.setTitle(_translate("MainWindow", "Material Properties", None))
        self.materialThicknessLabel_2.setText(_translate("MainWindow", "Material Thickness", None))
        self.materialYDimensionLabel.setText(_translate("MainWindow", "Material Y Dimension", None))
        self.materialXDimensionLabel.setText(_translate("MainWindow", "Material X Dimension", None))
        self.groupBox_7.setTitle(_translate("MainWindow", "Operation Origin", None))
        self.xOriginLabel.setText(_translate("MainWindow", "X Origin", None))
        self.yOriginLabel.setText(_translate("MainWindow", "Y Origin", None))
        self.setOriginFromGrid_pushButton.setText(_translate("MainWindow", "Set Origin From Grid", None))
        self.groupBox_4.setTitle(_translate("MainWindow", "Cut Vector", None))
        self.rightSideOfVectorLabel.setText(_translate("MainWindow", "Right Side of Vector", None))
        self.leftSideOfVectorLabel.setText(_translate("MainWindow", "Left Side of Vector", None))
        self.onVectorLabel.setText(_translate("MainWindow", "On Vector", None))
        self.cutReverseDirectionLabel.setText(_translate("MainWindow", "Cut Reverse Direction", None))
        self.p1XLabel.setText(_translate("MainWindow", "P1 X", None))
        self.p1YLabel.setText(_translate("MainWindow", "P1 Y", None))
        self.p2XLabel.setText(_translate("MainWindow", "P2 X", None))
        self.p2YLabel.setText(_translate("MainWindow", "P2 Y", None))
        self.groupBox_6.setTitle(_translate("MainWindow", "Tool Properties", None))
        self.toolDiameterLabel_3.setText(_translate("MainWindow", "Tool Diameter", None))
        self.cutterLengthLabel_3.setText(_translate("MainWindow", "Cutter Length", None))
        self.toolStickOutLabel_3.setText(_translate("MainWindow", "Tool Stick Out", None))
        self.groupBox_8.setTitle(_translate("MainWindow", "Operation Properties", None))
        self.safeZHeightLabel_2.setText(_translate("MainWindow", "Safe Z Height", None))
        self.overTravelLabel_2.setText(_translate("MainWindow", "Over Travel", None))
        self.zAxisOffsetLabel.setText(_translate("MainWindow", "Z Axis Offset", None))
        self.horizontalNibbleLabel.setText(_translate("MainWindow", "Horizontal Nibble", None))
        self.horizontalNibbleOffsetLabel.setText(_translate("MainWindow", "Horizontal Nibble Offset", None))
        self.finalPassesLabel_2.setText(_translate("MainWindow", "Final Passes", None))
        self.finalOffsetLabel_2.setText(_translate("MainWindow", "Final Offset", None))
        self.finalPassSpindleSpeedLabel_2.setText(_translate("MainWindow", "Final Pass Spindle Speed", None))
        self.finalPassFeedRateLabel_2.setText(_translate("MainWindow", "Final Pass Feed Rate", None))
        self.cutPassesLabel_2.setText(_translate("MainWindow", "Cut Passes", None))
        self.cutOffsetLabel_2.setText(_translate("MainWindow", "Cut Offset", None))
        self.cutPassSpindleSpeedLabel_2.setText(_translate("MainWindow", "Cut Pass Spindle Speed", None))
        self.cutPassFeedRateLabel_2.setText(_translate("MainWindow", "Cut Pass Feed Rate", None))
        self.moduleTabWidget.setTabText(self.moduleTabWidget.indexOf(self.tab_StraightCut), _translate("MainWindow", "Straight Cut", None))
        self.launchFeedAndSpeeds_pushButton.setText(_translate("MainWindow", "F&S Calc", None))
        self.loadTool_pushButton.setText(_translate("MainWindow", "Load Tool", None))
        self.generateGCode_pushButton.setText(_translate("MainWindow", "Generate g-Code", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuSettings.setTitle(_translate("MainWindow", "Settings", None))
        self.menuTools.setTitle(_translate("MainWindow", "Tools", None))
        self.actionExit.setText(_translate("MainWindow", "Exit", None))
        self.actionMachine.setText(_translate("MainWindow", "Machine", None))
        self.actionGrid.setText(_translate("MainWindow", "Grid", None))
        self.actionPreamble.setText(_translate("MainWindow", "Preamble", None))
        self.actionPostamble.setText(_translate("MainWindow", "Postamble", None))
        self.actionCalc_Work_Offset.setText(_translate("MainWindow", "Calc Work Offset", None))
        self.actionTool_Database.setText(_translate("MainWindow", "Tool Database", None))
        self.actionDefault_GCode_Folder.setText(_translate("MainWindow", "Default GCode Folder", None))

