# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Main.ui'
#
# Created: Sun Jan 26 19:32:57 2014
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(862, 592)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.moduleTabWidget = QtGui.QTabWidget(self.centralwidget)
        self.moduleTabWidget.setObjectName(_fromUtf8("moduleTabWidget"))
        self.tab_Jointer = QtGui.QWidget()
        self.tab_Jointer.setObjectName(_fromUtf8("tab_Jointer"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.tab_Jointer)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.textBrowser_Jointer_Setup = QtGui.QTextBrowser(self.tab_Jointer)
        self.textBrowser_Jointer_Setup.setEnabled(True)
        self.textBrowser_Jointer_Setup.setFocusPolicy(QtCore.Qt.NoFocus)
        self.textBrowser_Jointer_Setup.setFrameShape(QtGui.QFrame.NoFrame)
        self.textBrowser_Jointer_Setup.setFrameShadow(QtGui.QFrame.Plain)
        self.textBrowser_Jointer_Setup.setObjectName(_fromUtf8("textBrowser_Jointer_Setup"))
        self.verticalLayout_3.addWidget(self.textBrowser_Jointer_Setup)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.groupBox = QtGui.QGroupBox(self.tab_Jointer)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_5 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.gridLayout_7 = QtGui.QGridLayout()
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.selectAxisLabel = QtGui.QLabel(self.groupBox)
        self.selectAxisLabel.setObjectName(_fromUtf8("selectAxisLabel"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.selectAxisLabel)
        self.comboBox_Jointer_SelectXYAxis = QtGui.QComboBox(self.groupBox)
        self.comboBox_Jointer_SelectXYAxis.setObjectName(_fromUtf8("comboBox_Jointer_SelectXYAxis"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.comboBox_Jointer_SelectXYAxis)
        self.overTravelLabel = QtGui.QLabel(self.groupBox)
        self.overTravelLabel.setObjectName(_fromUtf8("overTravelLabel"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.overTravelLabel)
        self.overTravelLineEdit = QtGui.QLineEdit(self.groupBox)
        self.overTravelLineEdit.setObjectName(_fromUtf8("overTravelLineEdit"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.overTravelLineEdit)
        self.feedRateLabel = QtGui.QLabel(self.groupBox)
        self.feedRateLabel.setObjectName(_fromUtf8("feedRateLabel"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.feedRateLabel)
        self.feedRateLineEdit = QtGui.QLineEdit(self.groupBox)
        self.feedRateLineEdit.setObjectName(_fromUtf8("feedRateLineEdit"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.feedRateLineEdit)
        self.spindleSpeedLabel = QtGui.QLabel(self.groupBox)
        self.spindleSpeedLabel.setObjectName(_fromUtf8("spindleSpeedLabel"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.spindleSpeedLabel)
        self.spindleSpeedLineEdit = QtGui.QLineEdit(self.groupBox)
        self.spindleSpeedLineEdit.setObjectName(_fromUtf8("spindleSpeedLineEdit"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.spindleSpeedLineEdit)
        self.safeZHeightLabel = QtGui.QLabel(self.groupBox)
        self.safeZHeightLabel.setObjectName(_fromUtf8("safeZHeightLabel"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.safeZHeightLabel)
        self.safeZHeightLineEdit = QtGui.QLineEdit(self.groupBox)
        self.safeZHeightLineEdit.setObjectName(_fromUtf8("safeZHeightLineEdit"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.safeZHeightLineEdit)
        self.gridLayout_7.addLayout(self.formLayout, 0, 0, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_7, 0, 0, 1, 1)
        self.gridLayout_8 = QtGui.QGridLayout()
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.formLayout_7 = QtGui.QFormLayout()
        self.formLayout_7.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_7.setObjectName(_fromUtf8("formLayout_7"))
        self.cutPassesLabel = QtGui.QLabel(self.groupBox)
        self.cutPassesLabel.setObjectName(_fromUtf8("cutPassesLabel"))
        self.formLayout_7.setWidget(0, QtGui.QFormLayout.LabelRole, self.cutPassesLabel)
        self.cutPassesSpinBox = QtGui.QSpinBox(self.groupBox)
        self.cutPassesSpinBox.setObjectName(_fromUtf8("cutPassesSpinBox"))
        self.formLayout_7.setWidget(0, QtGui.QFormLayout.FieldRole, self.cutPassesSpinBox)
        self.cutOffsetLabel = QtGui.QLabel(self.groupBox)
        self.cutOffsetLabel.setObjectName(_fromUtf8("cutOffsetLabel"))
        self.formLayout_7.setWidget(1, QtGui.QFormLayout.LabelRole, self.cutOffsetLabel)
        self.cutOffsetLineEdit = QtGui.QLineEdit(self.groupBox)
        self.cutOffsetLineEdit.setObjectName(_fromUtf8("cutOffsetLineEdit"))
        self.formLayout_7.setWidget(1, QtGui.QFormLayout.FieldRole, self.cutOffsetLineEdit)
        self.finalPassesLabel = QtGui.QLabel(self.groupBox)
        self.finalPassesLabel.setObjectName(_fromUtf8("finalPassesLabel"))
        self.formLayout_7.setWidget(2, QtGui.QFormLayout.LabelRole, self.finalPassesLabel)
        self.finalPassesSpinBox = QtGui.QSpinBox(self.groupBox)
        self.finalPassesSpinBox.setMinimum(1)
        self.finalPassesSpinBox.setObjectName(_fromUtf8("finalPassesSpinBox"))
        self.formLayout_7.setWidget(2, QtGui.QFormLayout.FieldRole, self.finalPassesSpinBox)
        self.zAxisOffsetLabel = QtGui.QLabel(self.groupBox)
        self.zAxisOffsetLabel.setObjectName(_fromUtf8("zAxisOffsetLabel"))
        self.formLayout_7.setWidget(4, QtGui.QFormLayout.LabelRole, self.zAxisOffsetLabel)
        self.zAxisOffsetLineEdit = QtGui.QLineEdit(self.groupBox)
        self.zAxisOffsetLineEdit.setObjectName(_fromUtf8("zAxisOffsetLineEdit"))
        self.formLayout_7.setWidget(4, QtGui.QFormLayout.FieldRole, self.zAxisOffsetLineEdit)
        self.finalOffsetLabel = QtGui.QLabel(self.groupBox)
        self.finalOffsetLabel.setObjectName(_fromUtf8("finalOffsetLabel"))
        self.formLayout_7.setWidget(3, QtGui.QFormLayout.LabelRole, self.finalOffsetLabel)
        self.finalOffsetLineEdit = QtGui.QLineEdit(self.groupBox)
        self.finalOffsetLineEdit.setObjectName(_fromUtf8("finalOffsetLineEdit"))
        self.formLayout_7.setWidget(3, QtGui.QFormLayout.FieldRole, self.finalOffsetLineEdit)
        self.gridLayout_8.addLayout(self.formLayout_7, 0, 0, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_8, 0, 1, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox, 0, 0, 1, 1)
        self.groupBox_2 = QtGui.QGroupBox(self.tab_Jointer)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.gridLayout_6 = QtGui.QGridLayout()
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.formLayout_2 = QtGui.QFormLayout()
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.materialLengthLabel = QtGui.QLabel(self.groupBox_2)
        self.materialLengthLabel.setObjectName(_fromUtf8("materialLengthLabel"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.materialLengthLabel)
        self.materialLengthLineEdit = QtGui.QLineEdit(self.groupBox_2)
        self.materialLengthLineEdit.setObjectName(_fromUtf8("materialLengthLineEdit"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.materialLengthLineEdit)
        self.materialWidthLabel = QtGui.QLabel(self.groupBox_2)
        self.materialWidthLabel.setObjectName(_fromUtf8("materialWidthLabel"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.materialWidthLabel)
        self.materialWidthLineEdit = QtGui.QLineEdit(self.groupBox_2)
        self.materialWidthLineEdit.setObjectName(_fromUtf8("materialWidthLineEdit"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.materialWidthLineEdit)
        self.materialThicknessLabel = QtGui.QLabel(self.groupBox_2)
        self.materialThicknessLabel.setObjectName(_fromUtf8("materialThicknessLabel"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.materialThicknessLabel)
        self.materialThicknessLineEdit = QtGui.QLineEdit(self.groupBox_2)
        self.materialThicknessLineEdit.setObjectName(_fromUtf8("materialThicknessLineEdit"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.materialThicknessLineEdit)
        self.distFromOriginLabel = QtGui.QLabel(self.groupBox_2)
        self.distFromOriginLabel.setObjectName(_fromUtf8("distFromOriginLabel"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.LabelRole, self.distFromOriginLabel)
        self.distFromOriginLineEdit = QtGui.QLineEdit(self.groupBox_2)
        self.distFromOriginLineEdit.setObjectName(_fromUtf8("distFromOriginLineEdit"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.FieldRole, self.distFromOriginLineEdit)
        self.gridLayout_6.addLayout(self.formLayout_2, 0, 0, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_6, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_2, 0, 1, 1, 1)
        self.groupBox_3 = QtGui.QGroupBox(self.tab_Jointer)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.formLayout_3 = QtGui.QFormLayout()
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.toolDiameterLabel = QtGui.QLabel(self.groupBox_3)
        self.toolDiameterLabel.setObjectName(_fromUtf8("toolDiameterLabel"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.toolDiameterLabel)
        self.toolDiameterLineEdit = QtGui.QLineEdit(self.groupBox_3)
        self.toolDiameterLineEdit.setObjectName(_fromUtf8("toolDiameterLineEdit"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.toolDiameterLineEdit)
        self.cutterLengthLabel = QtGui.QLabel(self.groupBox_3)
        self.cutterLengthLabel.setObjectName(_fromUtf8("cutterLengthLabel"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.LabelRole, self.cutterLengthLabel)
        self.cutterLengthLineEdit = QtGui.QLineEdit(self.groupBox_3)
        self.cutterLengthLineEdit.setObjectName(_fromUtf8("cutterLengthLineEdit"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.FieldRole, self.cutterLengthLineEdit)
        self.toolStickOutLabel = QtGui.QLabel(self.groupBox_3)
        self.toolStickOutLabel.setObjectName(_fromUtf8("toolStickOutLabel"))
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.LabelRole, self.toolStickOutLabel)
        self.toolStickOutLineEdit = QtGui.QLineEdit(self.groupBox_3)
        self.toolStickOutLineEdit.setObjectName(_fromUtf8("toolStickOutLineEdit"))
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.FieldRole, self.toolStickOutLineEdit)
        self.gridLayout.addLayout(self.formLayout_3, 0, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_3, 0, 2, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_3)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.moduleTabWidget.addTab(self.tab_Jointer, _fromUtf8(""))
        self.tab_StraightRip = QtGui.QWidget()
        self.tab_StraightRip.setObjectName(_fromUtf8("tab_StraightRip"))
        self.moduleTabWidget.addTab(self.tab_StraightRip, _fromUtf8(""))
        self.verticalLayout.addWidget(self.moduleTabWidget)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.launchFeedAndSpeedspushButton = QtGui.QPushButton(self.centralwidget)
        self.launchFeedAndSpeedspushButton.setObjectName(_fromUtf8("launchFeedAndSpeedspushButton"))
        self.horizontalLayout_2.addWidget(self.launchFeedAndSpeedspushButton)
        self.loadToolpushButton = QtGui.QPushButton(self.centralwidget)
        self.loadToolpushButton.setObjectName(_fromUtf8("loadToolpushButton"))
        self.horizontalLayout_2.addWidget(self.loadToolpushButton)
        self.generateGCodePushButton = QtGui.QPushButton(self.centralwidget)
        self.generateGCodePushButton.setAutoDefault(True)
        self.generateGCodePushButton.setObjectName(_fromUtf8("generateGCodePushButton"))
        self.horizontalLayout_2.addWidget(self.generateGCodePushButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 862, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuSettings = QtGui.QMenu(self.menubar)
        self.menuSettings.setObjectName(_fromUtf8("menuSettings"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionMachine = QtGui.QAction(MainWindow)
        self.actionMachine.setObjectName(_fromUtf8("actionMachine"))
        self.actionGrid = QtGui.QAction(MainWindow)
        self.actionGrid.setObjectName(_fromUtf8("actionGrid"))
        self.actionPreamble = QtGui.QAction(MainWindow)
        self.actionPreamble.setObjectName(_fromUtf8("actionPreamble"))
        self.actionPostamble = QtGui.QAction(MainWindow)
        self.actionPostamble.setObjectName(_fromUtf8("actionPostamble"))
        self.menuFile.addAction(self.actionExit)
        self.menuSettings.addAction(self.actionMachine)
        self.menuSettings.addAction(self.actionGrid)
        self.menuSettings.addAction(self.actionPreamble)
        self.menuSettings.addAction(self.actionPostamble)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())

        self.retranslateUi(MainWindow)
        self.moduleTabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.actionExit, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.comboBox_Jointer_SelectXYAxis, self.overTravelLineEdit)
        MainWindow.setTabOrder(self.overTravelLineEdit, self.feedRateLineEdit)
        MainWindow.setTabOrder(self.feedRateLineEdit, self.spindleSpeedLineEdit)
        MainWindow.setTabOrder(self.spindleSpeedLineEdit, self.safeZHeightLineEdit)
        MainWindow.setTabOrder(self.safeZHeightLineEdit, self.cutPassesSpinBox)
        MainWindow.setTabOrder(self.cutPassesSpinBox, self.cutOffsetLineEdit)
        MainWindow.setTabOrder(self.cutOffsetLineEdit, self.finalPassesSpinBox)
        MainWindow.setTabOrder(self.finalPassesSpinBox, self.finalOffsetLineEdit)
        MainWindow.setTabOrder(self.finalOffsetLineEdit, self.zAxisOffsetLineEdit)
        MainWindow.setTabOrder(self.zAxisOffsetLineEdit, self.materialLengthLineEdit)
        MainWindow.setTabOrder(self.materialLengthLineEdit, self.materialWidthLineEdit)
        MainWindow.setTabOrder(self.materialWidthLineEdit, self.materialThicknessLineEdit)
        MainWindow.setTabOrder(self.materialThicknessLineEdit, self.distFromOriginLineEdit)
        MainWindow.setTabOrder(self.distFromOriginLineEdit, self.toolDiameterLineEdit)
        MainWindow.setTabOrder(self.toolDiameterLineEdit, self.cutterLengthLineEdit)
        MainWindow.setTabOrder(self.cutterLengthLineEdit, self.toolStickOutLineEdit)
        MainWindow.setTabOrder(self.toolStickOutLineEdit, self.launchFeedAndSpeedspushButton)
        MainWindow.setTabOrder(self.launchFeedAndSpeedspushButton, self.loadToolpushButton)
        MainWindow.setTabOrder(self.loadToolpushButton, self.generateGCodePushButton)
        MainWindow.setTabOrder(self.generateGCodePushButton, self.moduleTabWidget)
        MainWindow.setTabOrder(self.moduleTabWidget, self.textBrowser_Jointer_Setup)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "CNC Woodworking g-code Generator", None))
        self.groupBox.setTitle(_translate("MainWindow", "Operation Properties", None))
        self.selectAxisLabel.setText(_translate("MainWindow", "Select Axis", None))
        self.overTravelLabel.setText(_translate("MainWindow", "Over Travel", None))
        self.feedRateLabel.setText(_translate("MainWindow", "Feed Rate", None))
        self.spindleSpeedLabel.setText(_translate("MainWindow", "Spindle Speed", None))
        self.safeZHeightLabel.setText(_translate("MainWindow", "Safe Z Height", None))
        self.cutPassesLabel.setText(_translate("MainWindow", "Cut Passes", None))
        self.cutOffsetLabel.setText(_translate("MainWindow", "Cut Offset", None))
        self.finalPassesLabel.setText(_translate("MainWindow", "Final Passes", None))
        self.zAxisOffsetLabel.setText(_translate("MainWindow", "Z Axis Offset", None))
        self.finalOffsetLabel.setText(_translate("MainWindow", "Final Offset", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "Material Properties", None))
        self.materialLengthLabel.setText(_translate("MainWindow", "Material Length", None))
        self.materialWidthLabel.setText(_translate("MainWindow", "Material Width", None))
        self.materialThicknessLabel.setText(_translate("MainWindow", "Material Thickness", None))
        self.distFromOriginLabel.setText(_translate("MainWindow", "Dist from Origin", None))
        self.groupBox_3.setTitle(_translate("MainWindow", "Tool Properties", None))
        self.toolDiameterLabel.setText(_translate("MainWindow", "Tool Diameter", None))
        self.cutterLengthLabel.setText(_translate("MainWindow", "Cutter Length", None))
        self.toolStickOutLabel.setText(_translate("MainWindow", "Tool Stick Out", None))
        self.moduleTabWidget.setTabText(self.moduleTabWidget.indexOf(self.tab_Jointer), _translate("MainWindow", "Jointer", None))
        self.moduleTabWidget.setTabText(self.moduleTabWidget.indexOf(self.tab_StraightRip), _translate("MainWindow", "Straight Rip", None))
        self.launchFeedAndSpeedspushButton.setText(_translate("MainWindow", "F&S Calc", None))
        self.loadToolpushButton.setText(_translate("MainWindow", "Load Tool", None))
        self.generateGCodePushButton.setText(_translate("MainWindow", "Generate g-Code", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuSettings.setTitle(_translate("MainWindow", "Settings", None))
        self.actionExit.setText(_translate("MainWindow", "Exit", None))
        self.actionMachine.setText(_translate("MainWindow", "Machine", None))
        self.actionGrid.setText(_translate("MainWindow", "Grid", None))
        self.actionPreamble.setText(_translate("MainWindow", "Preamble", None))
        self.actionPostamble.setText(_translate("MainWindow", "Postamble", None))

